### ISSUE TITLE
Float vertical not overridden when station subsequently freed

### ISSUE THREAD

**Issue by ndonnelly** [linz/snap#109]
Using the following commands in a 3d adjustment:

```
float WGTT NLSN KAIK
free KAIK
```

the expected behaviour is that WGTT and NLSN are floated and KAIK is free

Current behaviour is that WGTT, NLSN and the **_vertical_** component of KAIK are floated and the horizontal component of KAIK is free
[float_bug.zip](https://github.com/linz/snap/files/8714338/float_bug.zip)

**Comment by ccrook** [comment]
Noted: Thanks for excellent tiny example data set Nic.  Odd and not at all expected behavour.

**Comment by ccrook** [comment]
Issue fixed in source code.  Impact of error is free command will always remove horizontal float and never remove vertical float setting.
