### ISSUE TITLE
Increase number of decimal places in CSV angle observation output format.

### ISSUE THREAD

**Issue by ccrook** [linz/snap#30]
For first order triangulation angles are recorded to 0.01".  We want this to be preserved when converted to decimal degrees and back - requires 6dp.

**Comment by ndonnelly** [comment]
L P Lee's 1978 technical report "First order geodetic triangulation of New Zealand" has the details of the precision of NZGD49 geodetic observations on page 21. Second and third order were recorded to 0.01" and first order was actually to 0.001". However retaining an accuracy equivalent to 0.01" should be more than sufficient even for 1st Order. The report notes that observations were recorded to at least one extra degree of precision than was actually achievable in reality. 

@JefferyLiangNZ and @mermy may be interested in this as well.

**Comment by ccrook** [comment]
Turns out SNAP already handles this with the output_precision command in a command or configuration file.  eg

output_precision ha 2 

will retain the equivalent of 2 decimal places of a second
