### ISSUE TITLE
dat2site - WGS84 error message

### ISSUE THREAD

**Issue by ndonnelly** [linz/snap#40]
When running "Calc missing stations" in SNAP Manager using a "GB" csv file, there is a warning displayed

"Warning: Coordinate system WGS84 is not defined"

This is likely due to coordsys.def being updated to reference WGS84 more rigorously as separate frames, so may need to update dat2site to reflect this.

**Comment by ccrook** [comment]
@ndonnelly Hi Nic ... just seen this.  Do you have small sample you could upload please?

**Comment by ndonnelly** [comment]
[test_20180430.zip](https://github.com/linz/snap/files/1959311/test_20180430.zip)

@ccrook Simple dataset attached. Open it in SNAP and "Calc missing stations" and you'll see the warning. The coordinates still get calculated since this is only a warning.

**Comment by ccrook** [comment]
Fixed in 594a4014f304824e872b55d5805e44c3ae6c03a1
Thanks for test data - made it very easy :-)
