### ISSUE TITLE
Add capability to run batch file when starting DOS Window from SNAP

### ISSUE THREAD

**Issue by ndonnelly** [linz/snap#44]
There are sometimes commands that need to be run every time a DOS Window is opened from SNAP. For example, you may need to add a specific directory to the PATH environment variable. It would be useful if such commands could be added to a user defined batch file at a defined location and automatically run whenever a SNAP window is started.

**Comment by ccrook** [comment]
linz package updated to provide an option for running a DOS startup batch file.
